dist: trusty
language: python
python:
  - '3.6'

# Install tox and codecov
install:
  - pip install tox-travis
  - pip install codecov

# Use tox to run tests in the matrix of environments
script:
- tox -r

# Push the results back to codecov
after_success:
  - coverage xml && codecov -f coverage.xml --commit=$TRAVIS_COMMIT

# Deploy updates on master to pypi, which will only succeed if there's been a version bump
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  edge: true
  user: octue
  password:
    secure: "fmNaOhOXibvvRhM9bsRm5oszESakkBypsv0m0oI8DaKo+gtsHcSZI1j1n1PsH3Kj3U99jLs23ix94cICc39Uyf8MVQ/BqPwphLx7PFREYxi59UItk31Y9l/OAhF8WK5gTXdbVhQKyM+7IR9E6mxKrfVauEMIBnxXbMEqDn3YzmbLkPE48cYB/dC56NI68iSrB94wAyQf3QDyLn5JowH/e7oYcPdK35xLHR22+rGM4D8aHLLRi2ARNTEUaIqaSBnTxhqDR7ITPl5PF81YPAeogDHvCR/R9q3ZGRWyCe6Dg5+ZDWtxjXGLskXpNDRQhDJ2QLYYgocrkNpfIl/dUbR5fNkwGKL5kCvbwFpHnKsVdJ4oFYo5JBE2WWeVN+FYgcjtxBUcNZjsf2C4ff9kXDwzCUIVg/C1V/mlVHCQdRauGxCVFtl1u6j3RNrQ3n4Bs/cdyXjG8x2RNk+PQtTQmwCRNO88A1BVwtlYxeFXbjN+eY8mDVJ0j53hsOTQMrn4EESnUGJznHcfIpgwQKb0dzkv4JoVkCIldDp0GwOOmeWu6uo6JBfd9/SjaFqJFlYO1cYejZRNjiNFBQ+NE0XBrvrBfozeob6FVdg1I0cIUqjnZHPYCwb3COAuIpYjmRq6EfeQKjY8GgrXvJTYamm5XNzAMlQqCnEUCCPUqGPxacKbTEQ="
  on:
    branch: master
