[tool.poetry]
name = "octue-sdk-python"
version = "0.15.6"
description = "A package providing template applications for data services, and a python SDK to the Octue API."
authors = ["Thomas Clark, cortadocodes <cortado.codes@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
coolname = "^1.1.0"
Flask = "^1.1"
google-auth = ">=1.27.0, <3"
google-cloud-pubsub = "^2.5.0"
google-cloud-secret-manager = "^2.3.0"
google-cloud-storage = "^1.35.1"
google-crc32c = "^1.1.2"
gunicorn = "^20.1.0"
python-dateutil = "^2.8.1"
pyyaml = "^6"
twined = "0.2.2"

h5py = { version = "^3.6.0", optional = true }
apache-beam = { version = "2.37.0", optional = true }

[tool.poetry.extras]
hdf5 = ["h5py"]
dataflow = ["apache-beam[gcp]"]

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
