name: build-docker-image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for Docker image'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          tags: octue/octue-sdk-python:${{ github.event.inputs.tag }}"
