name: check-version-consistency
on: [push]
jobs:
  check-version-consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python setup.py --version
      - run: pwd
