name: Release the package on merge into main

# Only trigger when a pull request into main branch is closed.
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: github.event.pull_request.merged == true && "!contains(github.event.pull_request.head.message, 'skip_ci_release')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Set fetch-depth to 0 to fetch all commit history (necessary for compiling release notes).
        fetch-depth: 0
    - name: Get package version
      run: echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
    - name: Compile release notes
      run: |
        echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
        echo "$(python .github/workflows/scripts/compile-release-notes.py RELEASE)" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: ${{ github.event.pull_request.title }}
        body: ${{ env.RELEASE_NOTES }}
        draft: false
        prerelease: false
