# Only trigger for pull requests into main branch.
on:
  pull_request:
    branches:
      - main

jobs:
  update-pull-request-description:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Set fetch-depth to 0 to fetch all commit history (necessary for compiling pull request description).
        fetch-depth: 0
    - name: Compile new pull request description
      run: |
        echo 'PULL_REQUEST_NOTES<<EOF' >> $GITHUB_ENV
        echo "$(python .github/workflows/scripts/compile-release-notes.py LAST_PULL_REQUEST '${{ github.event.pull_request.body }}')" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Update pull request body
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ env.PULL_REQUEST_NOTES }}
        token: ${{ secrets.GITHUB_TOKEN }}
